### ISSUE TITLE
disconnect from SS-GraphQL

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-graphql-jwt#2]
Could you separate out the JWT Authenticator in a standalone package? There’s no direct need to couple this with a GraphQL token generation

**Comment by Firesphere** [comment]
For the type-creator, I think we're stuck with the SS-GraphQL @chillu

**Comment by Firesphere** [comment]
@chillu, could you elaborate a bit on what was needed here? Because I don't really remember.

**Comment by chillu** [comment]
Hey Simon, from memory, my original point was around using SS4 HTTP middleware to login the member based on a JWT Bearer header. This way you can choose to only apply the middleware to certain routes: You might only want JWT auth in `/graphql`, not in `/admin`.

Token creation and validation could also be separated from GraphQL. Which means you could use the same authentication handler routines regardless how tokens were created (REST, RPC, GraphQL, etc). So in essence, you could split out https://github.com/Firesphere/silverstripe-graphql-jwt/blob/master/src/Authentication/JWTAuthenticator.php and https://github.com/Firesphere/silverstripe-graphql-jwt/blob/master/src/Authentication/JWTAuthenticationHandler.php. 

It's not a high priority until this module gets more use though

**Comment by Firesphere** [comment]
I'm going to close this issue. I do not feel it's relevant anymore. The module is tightly coupled to Silverstripe anyway, so.... why try to decouple something that is so tightly coupled?

@chillu If you feel I misunderstood your issue, feel free to open a new issue, or reopen this one.
