### ISSUE TITLE
I was trying to install `silverstripe-graphql-jwt` with silverstripe 4.3

### ISSUE THREAD

**Issue by jithinkradhakrishnan** [Firesphere/silverstripe-graphql-jwt#20]
getting dependency error
 Problem 1
    - Installation request for firesphere/silverstripe-graphql-jwt ^1.1 -> satisfiable by firesphere/silverstripe-graphql-jwt[1.1.0].
    - Conclusion: remove nikic/php-parser v4.1.1
    - Conclusion: don't install nikic/php-parser v4.1.1
    - firesphere/silverstripe-graphql-jwt 1.1.0 requires silverstripe/recipe-core ^1.0 -> satisfiable by silverstripe/recipe-core[1.0.x-dev, 1.1.x-dev, 1.x-dev, 1.2.x-dev].
    - silverstripe/recipe-core 1.0.x-dev requires silverstripe/framework 4.0.x-dev -> satisfiable by silverstripe/framework[4.0.x-dev].
    - silverstripe/recipe-core 1.1.x-dev requires silverstripe/framework 4.1.x-dev -> satisfiable by silverstripe/framework[4.1.x-dev].
    - silverstripe/recipe-core 1.x-dev requires silverstripe/framework 4.2.x-dev -> satisfiable by silverstripe/framework[4.2.x-dev].
    - silverstripe/recipe-core 1.2.x-dev requires silverstripe/framework 4.2.x-dev -> satisfiable by silverstripe/framework[4.2.x-dev].
    - silverstripe/framework 4.0.x-dev requires nikic/php-parser ^2 || ^3 -> satisfiable by nikic/php-parser[2.x-dev, 3.x-dev].
    - silverstripe/framework 4.1.x-dev requires nikic/php-parser ^2 || ^3 -> satisfiable by nikic/php-parser[2.x-dev, 3.x-dev].
    - silverstripe/framework 4.2.x-dev requires nikic/php-parser ^2 || ^3 -> satisfiable by nikic/php-parser[2.x-dev, 3.x-dev].
    - Can only install one of: nikic/php-parser[2.x-dev, v4.1.1].
    - Can only install one of: nikic/php-parser[3.x-dev, v4.1.1].
    - Installation request for nikic/php-parser (locked at v4.1.1, required as ^4.1) -> satisfiable by nikic/php-parser[v4.1.1].

also tried installing branch dev-master

**Comment by Firesphere** [comment]
I need to update the recipe-core version. It should be ^4 and it's currently at ^1. The version bump for the recipes has caused more errors recently

**Comment by Firesphere** [comment]
Try 2.0.0-beta1 please? That one should work

**Comment by ec8or** [comment]
Can confirm it works with 2.0.0-beta1

**Comment by chillu** [comment]
Would this be closed once you release a 2.0.0 stable? At the moment, `firesphere/graphql-jwt` doesn't work as described in the README on the latest stable of SS. Admittedly that's our fault for changing recipe versioning from 1.x to 4.x release lines on newer tags, but that could easily be fixed by changing that constraints in the `1.x` branch here on this module. We've created all tags back to `4.0.0`

**Comment by Firesphere** [comment]
I am looking to see if I can release a new stable indeed. Just a lack of time that caused the beta tag :)
Thanks @chillu :D
