### ISSUE TITLE
Describe how to generate signer key and what prefix is for

### ISSUE THREAD

**Issue by chillu** [Firesphere/silverstripe-graphql-jwt#21]
I think there's a lot of people who are not intimately familiar with JWT, and just want to use it as a standard way to authenticate. While you could force them to go read the HMAC RFC you linked to, they'll probably get stuck pretty soon ;) 

If you compare this to a similar laravel project, they have a task to generate a key and write it into the correct place: https://jwt-auth.readthedocs.io/en/develop/laravel-installation/

Admittedly, we should generate a random value with every SS install which can be used for purposes like this by default, but that's not a reality yet. So easier to fix in terms of module instructions, right?

**Comment by Firesphere** [comment]
Woah, old issues I'm trawling through!

Yeah, fair call! for asking this. I usually shy away from saying "Make a PR", but in this case, I think it's worth saying, it can be PR'd :) 

I personally do not have the time or energy at the moment, so a PR would be really helpful :)

**Comment by chillu** [comment]
Sweet, https://github.com/Firesphere/silverstripe-graphql-jwt/pull/33. I don't understand what the purpose of the prefix is, so I've left that out of the instructions.

**Comment by Firesphere** [comment]
Merged.

The prefix is simply... an option, not something important :D

**Comment by chillu** [comment]
Can you leave the prefix empty? If a value is required, maybe we suggest a default? At the moment it's very unclear whether this needs to be a randomised value, whether it shows up in payloads, and why you would use it in the first place. Happy to send a pull request clarifying that, but I don't understand it right now :D

**Comment by Firesphere** [comment]
It can easily be left empty, it's not really important, it's used to generate the Unique ID for each of the authentications.

It's basically a tiny useful thingy to keep your data structured. https://github.com/Firesphere/silverstripe-graphql-jwt/blob/master/src/Authentication/JWTAuthenticator.php#L232
