### ISSUE TITLE
Allow configuration of JWT settings

### ISSUE THREAD

**Issue by chillu** [Firesphere/silverstripe-graphql-jwt#3]
https://github.com/Firesphere/silverstripe-graphql-jwt/blob/master/src/Authentication/JWTAuthenticator.php#L54

`setExpiration()` and `sign()` come to mind

**Comment by Firesphere** [comment]
This has been setup in https://github.com/firesphere/silverstripe-graphql-jwt/commit/46ef3e61e4894fdd0788da85690581711661cdff
